### PR TITLE
node: commit proto and matching test fixes #1769

### LINKED ISSUE #1769: Provide generated proto files for go
## Expected Behavior
As a go integrator, I shouldn't have to generate the proto libraries from source. 

## Current Behavior
Integrators using go must pull the protos and generate the libraries from source in order to depend on anything in `node` or cleanly hit the gRPC endpoints. Guardians / 

## Possible Solution
Commit the generated proto files and add a CI step to ensure the committed files match a fresh build from the same commit (to keep them in sync).

## Context (Environment)
Building an indexer for the wormhole ecosystem.

### PR DESCRIPTION
**Pull request by evan-gray**
Anyone including the node code as a dependency from github breaks on the missing protos. This PR adds the generated go protos along with a CI check to ensure they always match the protos themselves. Added bonus there's one less step for Tilt to do.

### CODE REVIEW

**Comment by evan-gray** [comment]
evidence of test breaking when a proto change is made without committing the corresponding generated code: https://github.com/wormhole-foundation/wormhole/actions/runs/3349436581/jobs/5549438027

**Comment by evan-gray** [comment]
proving a failure case by manipulating the generated go code https://github.com/wormhole-foundation/wormhole/actions/runs/3349468198/jobs/5549500358

**Comment by hendrikhofstadt** [comment]
For awareness @conorpp

**Review by hendrikhofstadt — CHANGES_REQUESTED** [review]
Please document the proto compiler step in `DEVELOP.md` or a similar place

**Review by kcsongor — APPROVED** [review]

**Pull request merged**
