### PR TITLE
Ensure optin transaction is the current transaction and address the a…

### PR DESCRIPTION
**Pull request by marcosnc**
…lgo_seed transaction in a relative manner.

### CODE REVIEW

**Review by hernandp — APPROVED** [review]
looks good ;)

**Review by jumpsiegel — APPROVED** [review]

**Review by jumpsiegel — APPROVED** [review]

**Comment by marcosnc** [comment]
> The change seems sensible, it allows the optin transaction to appear anywhere within a group rather than only at the beginning, right? I'm a little confused why `admin.py` needs to change due to this -- in the comment message you mention that it's to fix a test. Can you explain why the test fails after allowing optin to appear anywhere within a group, and how the length check fixes that failure? Thanks!

Indeed, the change ensures the validations are done on the actual optin, the one received, instead of the one in the absolute position 1.
Regarding the `admin.py` change, it seemed the test was failing with something not related to this change and I followed the recommendations from @barnjamin.

**Comment by barnjamin** [comment]
The admin.py change was necessary because the VAA parser was overwriting some fields since the test VAA happened to have a `3` in the offset being checked. The change here is a bit smelly but it works to make the tests pass. 

Fwiw I did rework the parser today here, though its not thoroughly tested.
https://github.com/barnjamin/wh-metrics/blob/main/vaa.py

**Comment by kcsongor** [comment]
thanks @marcosnc!

**Review by kcsongor — APPROVED** [review]

**Pull request merged**
