### PR TITLE
client/js: update wormhole-foundation/sdk (0.9.0) and certusone/wormhole-sdk (0.10.17)

### PR DESCRIPTION
**Pull request by andreclaro**
client/js: update wormhole-foundation/sdk (0.9.0) and certusone/wormhole-sdk (0.10.17)

### CODE REVIEW

**Comment by zjb0807** [comment]
https://github.com/andreclaro/wormhole/blob/48a07af511f3a74c51527bbfa9e144341053397c/clients/js/src/consts/networks.ts#L339 Please help to update the chainId to `597`

**Comment by andreclaro** [comment]
> https://github.com/andreclaro/wormhole/blob/48a07af511f3a74c51527bbfa9e144341053397c/clients/js/src/consts/networks.ts#L339 Please help to update the chainId to `597`

wormhole now uses wormhole-sdk-ts (https://github.com/wormhole-foundation/wormhole-sdk-ts), which seems to be up-to-date.

@bruce-riley , can we still update  https://github.com/andreclaro/wormhole/blob/48a07af511f3a74c51527bbfa9e144341053397c/clients/js/src/consts/networks.ts#L339 ? Thanks

**Comment by bruce-riley** [comment]
> > https://github.com/andreclaro/wormhole/blob/48a07af511f3a74c51527bbfa9e144341053397c/clients/js/src/consts/networks.ts#L339 Please help to update the chainId to `597`
> 
> wormhole now uses wormhole-sdk-ts (https://github.com/wormhole-foundation/wormhole-sdk-ts), which seems to be up-to-date.
> 
> @bruce-riley , can we still update https://github.com/andreclaro/wormhole/blob/48a07af511f3a74c51527bbfa9e144341053397c/clients/js/src/consts/networks.ts#L339 ? Thanks

Yes, I think for now you should still update that. Thanks!

**Comment by evan-gray** [comment]
@andreclaro  there are often more changes involved when bumping a dependency. See the cli test errors. Probably would benefit from trying to ensure the code builds before putting up a PR.

**Comment by andreclaro** [comment]
> @andreclaro there are often more changes involved when bumping a dependency. See the cli test errors. Probably would benefit from trying to ensure the code builds before putting up a PR.

yes, you are right! This was a draft PR.

**Comment by andreclaro** [comment]
I also see the issues when running `npm run check` locally...

**Comment by andreclaro** [comment]
@panoel will take a look at this as he is leading the migration from SDKv1 to SDKv2. Thank you Sir!

**Review by evan-gray — APPROVED** [review]

**Review by panoel — APPROVED** [review]

**Pull request merged**
