### PR TITLE
clients/eth: update dependencies

### PR DESCRIPTION
**Pull request by tbjump**

### CODE REVIEW

**Comment by tbjump** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3047** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3047" target="_blank">Graphite</a> 
    * **PR #3056** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3056" target="_blank">Graphite</a>  👈
      * **PR #3055** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3055" target="_blank">Graphite</a> 
    * **PR #3048** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3048" target="_blank">Graphite</a> 
      * **PR #3051** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3051" target="_blank">Graphite</a> 
        * **PR #3024** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3024" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3056?utm_source=stack-comment).

**Comment by tbjump** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3047** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3047" target="_blank">Graphite</a> 
    * **PR #3056** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3056" target="_blank">Graphite</a>  👈
      * **PR #3055** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3055" target="_blank">Graphite</a> 
    * **PR #3048** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3048" target="_blank">Graphite</a> 
      * **PR #3051** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3051" target="_blank">Graphite</a> 
        * **PR #3024** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3024" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3056?utm_source=stack-comment).

**Review by kcsongor — APPROVED** [review]
is this code used anywhere? should we just delete it?

**Comment by tbjump** [comment]
It's used in this guardian set update check in Tilt. https://github.com/wormhole-foundation/wormhole/blob/0ecc427d6fe7f1e2c9a39cc023ab0b094f13ede0/Tiltfile#L346

**Review by SEJeff — APPROVED** [review]

**Review by bruce-riley — APPROVED** [review]

**Pull request merged**
