### PR TITLE
WH-1934: upgrade golang to 1.19

### LINKED ISSUE #1934: Upgrade golang from 1.17 to 1.19
Upgrade golang from 1.17 to 1.19

### PR DESCRIPTION
**Pull request by jumpsiegel**
WH-1934: upgrade golang to 1.19 @ Closes #1934

### CODE REVIEW

**Comment by tbjump** [comment]
Here's one more place: https://github.com/wormhole-foundation/wormhole/blob/f60e6669ec5e65ca2390a6ac10b834d2dec5821a/.github/workflows/build.yml#L254

**Comment by kcsongor** [comment]
does changing the docker images have any material effect on the actual toolchains being used?
to me it seems these files need to be updated too
https://github.com/wormhole-foundation/wormhole/blob/5c0ed392d464d02de1d4bcb2d5ac4e4cedcb7a2c/node/go.mod#L3
https://github.com/wormhole-foundation/wormhole/blob/5c0ed392d464d02de1d4bcb2d5ac4e4cedcb7a2c/sdk/go.mod#L3
https://github.com/wormhole-foundation/wormhole/blob/5c0ed392d464d02de1d4bcb2d5ac4e4cedcb7a2c/tools/go.mod#L3
https://github.com/wormhole-foundation/wormhole/blob/5c0ed392d464d02de1d4bcb2d5ac4e4cedcb7a2c/wormchain/go.mod#L3

**Review by tbjump — APPROVED** [review]
lgtm

**Comment by tbjump** [comment]
disabled the race condition detector in the dev build since it seemed to be overwhelmed and cause oom-kill

**Comment by tbjump** [comment]
Parsing the required reviewers from the CODEOWNERS: 
* @bruce-riley or @jynnantonix 
* @leoluk or @hendrikhofstadt 
* @bruce-riley or @claudijd 
* @evan-gray or @hendrikhofstadt 
* @jumpsiegel 

Smallest covering set: @bruce-riley @hendrikhofstadt @jumpsiegel

**Review by jynnantonix — APPROVED** [review]

**Review by hendrikhofstadt — APPROVED** [review]

**Review by bruce-riley — APPROVED** [review]

**Pull request merged**
