### PR TITLE
sui: add custom key support to deploy script

### LINKED ISSUE #2595: sui: update deploy script to take in custom private key
#2583 introduced the ability for the `worm` CLI to take in an arbitrary private key to the sign transactions in each command. We need to expose this functionality in `sui/scripts/deploy.sh`

### PR DESCRIPTION
**Pull request by heyitaki**
This PR updates the Sui deploy script to accept an optional `private-key` flag to allow for the use of a custom private key to sign transactions with. This is especially useful for contributors who are using a local Sui validator instead of Tilt, so that they can substitute the hardcoded active key from Tilt with their own.

Resolves #2595

### CODE REVIEW

**Comment by heyitaki** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2358** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2358" target="_blank">Graphite</a> 
    * **PR #2583** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2583" target="_blank">Graphite</a> 
    * **PR #2582** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2582" target="_blank">Graphite</a> 
    * **PR #2551** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2551" target="_blank">Graphite</a> 
    * **PR #2516** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2516" target="_blank">Graphite</a> 
    * **PR #2580** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2580" target="_blank">Graphite</a> 
    * **PR #2494** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2494" target="_blank">Graphite</a> 
    * **PR #2579** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2579" target="_blank">Graphite</a> 
    * **PR #2584** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2584" target="_blank">Graphite</a> 
      * **PR #2594** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2594" target="_blank">Graphite</a> 
        * **PR #2599** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2599" target="_blank">Graphite</a> 
          * **PR #2600** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600" target="_blank">Graphite</a>  👈
    * **PR #2559** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2559" target="_blank">Graphite</a> 
    * **PR #2534** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2534" target="_blank">Graphite</a> 
      * **PR #2547** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2547" target="_blank">Graphite</a> 
        * **PR #2549** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2549" target="_blank">Graphite</a> 
          * **PR #2557** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2557" target="_blank">Graphite</a> 
            * **PR #2558** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2558" target="_blank">Graphite</a> 
            * **PR #2576** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2576" target="_blank">Graphite</a> 
      * **PR #2578** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2578" target="_blank">Graphite</a> 
    * **PR #2543** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2543" target="_blank">Graphite</a> 
      * **PR #2544** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2544" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600?utm_source=stack-comment).

**Comment by heyitaki** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2358** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2358" target="_blank">Graphite</a> 
    * **PR #2583** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2583" target="_blank">Graphite</a> 
    * **PR #2582** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2582" target="_blank">Graphite</a> 
    * **PR #2551** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2551" target="_blank">Graphite</a> 
    * **PR #2516** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2516" target="_blank">Graphite</a> 
    * **PR #2580** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2580" target="_blank">Graphite</a> 
    * **PR #2494** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2494" target="_blank">Graphite</a> 
    * **PR #2579** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2579" target="_blank">Graphite</a> 
    * **PR #2584** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2584" target="_blank">Graphite</a> 
      * **PR #2594** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2594" target="_blank">Graphite</a> 
        * **PR #2599** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2599" target="_blank">Graphite</a> 
          * **PR #2600** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600" target="_blank">Graphite</a>  👈
    * **PR #2559** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2559" target="_blank">Graphite</a> 
    * **PR #2534** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2534" target="_blank">Graphite</a> 
      * **PR #2547** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2547" target="_blank">Graphite</a> 
        * **PR #2549** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2549" target="_blank">Graphite</a> 
          * **PR #2557** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2557" target="_blank">Graphite</a> 
            * **PR #2558** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2558" target="_blank">Graphite</a> 
            * **PR #2576** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2576" target="_blank">Graphite</a> 
      * **PR #2578** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2578" target="_blank">Graphite</a> 
    * **PR #2543** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2543" target="_blank">Graphite</a> 
      * **PR #2544** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2544" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600?utm_source=stack-comment).

**Comment by heyitaki** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2358** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2358" target="_blank">Graphite</a> 
    * **PR #2583** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2583" target="_blank">Graphite</a> 
    * **PR #2582** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2582" target="_blank">Graphite</a> 
    * **PR #2551** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2551" target="_blank">Graphite</a> 
    * **PR #2516** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2516" target="_blank">Graphite</a> 
    * **PR #2580** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2580" target="_blank">Graphite</a> 
    * **PR #2494** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2494" target="_blank">Graphite</a> 
    * **PR #2579** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2579" target="_blank">Graphite</a> 
    * **PR #2584** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2584" target="_blank">Graphite</a> 
      * **PR #2594** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2594" target="_blank">Graphite</a> 
        * **PR #2599** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2599" target="_blank">Graphite</a> 
          * **PR #2600** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600" target="_blank">Graphite</a>  👈
    * **PR #2559** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2559" target="_blank">Graphite</a> 
    * **PR #2534** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2534" target="_blank">Graphite</a> 
      * **PR #2547** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2547" target="_blank">Graphite</a> 
        * **PR #2549** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2549" target="_blank">Graphite</a> 
          * **PR #2557** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2557" target="_blank">Graphite</a> 
            * **PR #2558** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2558" target="_blank">Graphite</a> 
            * **PR #2576** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2576" target="_blank">Graphite</a> 
      * **PR #2578** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2578" target="_blank">Graphite</a> 
    * **PR #2543** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2543" target="_blank">Graphite</a> 
      * **PR #2544** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2544" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600?utm_source=stack-comment).

**Review by a5-pickle — APPROVED** [review]

**Comment by a5-pickle** [comment]
@a5-pickle queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600).

**Comment by a5-pickle** [comment]
[Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2600) couldn't merge this pull request because a downstack PR #2594 failed to merge.

**Pull request merged**
