### PR TITLE
add: safety check against signatory being address(0)

### PR DESCRIPTION
**Pull request by hendrikhofstadt**
Reopening #1897 by @Rassska which got auto closed (and couldn't be reopened) when I pushed the wrong branch to the remote.

### CODE REVIEW

**Review by kcsongor — DISMISSED** [review]
great patch

**Comment by jumpsiegel** [comment]
This breaks the ethereum test...

**Comment by Rassska** [comment]
Actually, I was expecting that some test cases with revert messages might fail if we move it up.

The question is, is this case 100% covered with another 2 requires? If it is, this additional check is redundant.

**Review by a5-pickle — DISMISSED** [review]
I pushed a commit that fixes the forge test. It doesn't feel right to approve these changes since I modified the PR, so leaving it for the other reviewers to look everything over.

**Review by jumpsiegel — APPROVED** [review]

**Review by kcsongor — APPROVED** [review]

**Pull request merged**
