### PR TITLE
Clients/js/fix near typos

### PR DESCRIPTION
**Pull request by AlberErre**
This PR fixes small `NEAR` typos from error messages on other chains functions (Solana, Sei)

@aadam-10 @heyitaki @a5-pickle

### CODE REVIEW

**Review by kcsongor — APPROVED** [review]
good catch!

**Review by heyitaki — CHANGES_REQUESTED** [review]
I think that these may be fixed in another PR, let's hold off on meeting for now

**Comment by heyitaki** [comment]
@AlberErre do you mind rebasing latest changes? Sei was patched in #2886 (https://github.com/wormhole-foundation/wormhole/blob/main/clients/js/src/chains/sei/submit.ts), but the Solana typo still exists, so lets get that merged in!

**Comment by AlberErre** [comment]
perfect! ✅ just rebased it @heyitaki 

Thanks!

**Comment by AlberErre** [comment]
just merged `main` to sync again ✅, but it looks like two approvals are needed 👀 , as well as running the pipelines.

@heyitaki  @kcsongor @aadam-10

**Review by kcsongor — APPROVED** [review]

**Pull request merged**
