### PR TITLE
wormchain: update ts sdk

### PR DESCRIPTION
**Pull request by justinschuldt**
Ran wormchain's `make ts-sdk` and updated `certusone.wormholechain` references to be `wormhole_foundation.wormchain`.
Add a CI step to ensure the output of `make ts-sdk` matches what is checked in, so ts-sdk stays up to date. Same process as do for proto gen.

### CODE REVIEW

**Comment by justinschuldt** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2296** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2296" target="_blank">Graphite</a> 
    * **PR #2297** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2297" target="_blank">Graphite</a> 
      * **PR #2298** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298" target="_blank">Graphite</a>  👈
        * **PR #2299** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2299" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298?utm_source=stack-comment).

**Comment by justinschuldt** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2296** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2296" target="_blank">Graphite</a> 
    * **PR #2297** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2297" target="_blank">Graphite</a> 
      * **PR #2298** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298" target="_blank">Graphite</a>  👈
        * **PR #2299** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2299" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298?utm_source=stack-comment).

**Review by conorpp — APPROVED** [review]

**Comment by conorpp** [comment]
Informational: I checked the ts-sdk generation diff and noticed mine had some imports & lists in different orders.   I hope it's because of a slight version change or something I have locally, but it might _not_ be deterministic.  Example:
```
 import { SigningStargateClient } from "@cosmjs/stargate";
 import { Registry, OfflineSigner, EncodeObject, DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
 import { Api } from "./rest";
-import { MsgExecuteGovernanceVAA } from "./types/wormhole/tx";
-import { MsgInstantiateContract } from "./types/wormhole/tx";
 import { MsgRegisterAccountAsGuardian } from "./types/wormhole/tx";
 import { MsgStoreCode } from "./types/wormhole/tx";
+import { MsgExecuteGovernanceVAA } from "./types/wormhole/tx";
+import { MsgInstantiateContract } from "./types/wormhole/tx";
 
 
 const types = [
-  ["/wormhole_foundation.wormchain.wormhole.MsgExecuteGovernanceVAA", MsgExecuteGovernanceVAA],
-  ["/wormhole_foundation.wormchain.wormhole.MsgInstantiateContract", MsgInstantiateContract],
   ["/wormhole_foundation.wormchain.wormhole.MsgRegisterAccountAsGuardian", MsgRegisterAccountAsGuardian],
   ["/wormhole_foundation.wormchain.wormhole.MsgStoreCode", MsgStoreCode],
+  ["/wormhole_foundation.wormchain.wormhole.MsgExecuteGovernanceVAA", MsgExecuteGovernanceVAA],
+  ["/wormhole_foundation.wormchain.wormhole.MsgInstantiateContract", MsgInstantiateContract],
   
 ];
 export const MissingWalletError = new Error("wallet is required");
@@ -48,10 +48,10 @@ const txClient = async (wallet: OfflineSigner, { addr: addr }: TxClientOptions =
 
   return {
     signAndBroadcast: (msgs: EncodeObject[], { fee, memo }: SignAndBroadcastOptions = {fee: defaultFee, memo: ""}) => client.signAndBroadcast(address, msgs, fee,memo),
-    msgExecuteGovernanceVAA: (data: MsgExecuteGovernanceVAA): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgExecuteGovernanceVAA", value: MsgExecuteGovernanceVAA.fromPartial( data ) }),
-    msgInstantiateContract: (data: MsgInstantiateContract): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgInstantiateContract", value: MsgInstantiateContract.fromPartial( data ) }),
     msgRegisterAccountAsGuardian: (data: MsgRegisterAccountAsGuardian): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgRegisterAccountAsGuardian", value: MsgRegisterAccountAsGuardian.fromPartial( data ) }),
     msgStoreCode: (data: MsgStoreCode): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgStoreCode", value: MsgStoreCode.fromPartial( data ) }),
+    msgExecuteGovernanceVAA: (data: MsgExecuteGovernanceVAA): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgExecuteGovernanceVAA", value: MsgExecuteGovernanceVAA.fromPartial( data ) }),
+    msgInstantiateContract: (data: MsgInstantiateContract): EncodeObject => ({ typeUrl: "/wormhole_foundation.wormchain.wormhole.MsgInstantiateContract", value: MsgInstantiateContract.fromPartial( data ) }),
     
   };
 };
```

**Review by evan-gray — CHANGES_REQUESTED** [review]
This is missing changes from https://github.com/wormhole-foundation/wormhole/pull/2290/commits/f3bf33ede0fc94f2e29cb77177e3782a8c1bcc95
The `wasm` package should be included as well. Without it, everything down stack fails.

**Review by evan-gray — DISMISSED** [review]
Also this errors in `wormchain` CI
https://github.com/wormhole-foundation/wormhole/actions/runs/4026508722/jobs/6923004439#step:5:1652

> Error: ENOENT: no such file or directory, scandir '../vue/src/store/generated/wormhole-foundation/wormchain/'

**Comment by justinschuldt** [comment]
@conorpp Re. non-deterministic `make ts-sdk`, hmm, good to know, thanks for running it. I think I figured out how to make it deterministic, testing now.

@evan-gray roger, will update

**Comment by justinschuldt** [comment]
@evan-gray i'm working on the CI fix rn, looks like if you run `make ts-sdk` after running `make proto -B` (as happens in CI) some deps are not satisfied, though the makefile cache thinks they are.

**Comment by justinschuldt** [comment]
Turns out `ignite generate vuex` is not deterministic :sob:

**Review by nik-suri — APPROVED** [review]
lgtm. re non-determinism, I think it would make sense in a follow up PR to completely remove ignite and generate ts and proto using our own scripts

**Comment by evan-gray** [comment]
> lgtm. re non-determinism, I think it would make sense in a follow up PR to completely remove ignite and generate ts and proto using our own scripts

Concur, though I believe vuex is deprecated. We could try the ts-client script first, or just switch to ts proto like the rest of our generation.

**Review by hendrikhofstadt — APPROVED** [review]

**Review by evan-gray — APPROVED** [review]

**Pull request merged**
