### PR TITLE
ci: unscoped npm package check

### PR DESCRIPTION
**Pull request by evan-gray**
Adding a check to ensure that packages in the repo are always scoped to the wormhole-foundation (or certusone, the current scope of the javasscript sdk and related packages) as is good practice.

### CODE REVIEW

**Comment by evan-gray** [comment]
Proof that the check works in the negative case.
https://github.com/wormhole-foundation/wormhole/actions/runs/3292916044/jobs/5428840422

**Comment by evan-gray** [comment]
Proof that the check works in the positive case https://github.com/wormhole-foundation/wormhole/actions/runs/3293029897/jobs/5429089321

**Review by kev1n-peters — APPROVED** [review]

**Review by tbjump — APPROVED** [review]
love it

**Comment by tbjump** [comment]
Side note: looks like you're doing some auto-formatting on save. Would be good to either disable that or make it part of https://github.com/wormhole-foundation/wormhole/blob/dev.v2/scripts/lint.sh because it makes the PR harder to review.

**Comment by evan-gray** [comment]
> Side note: looks like you're doing some auto-formatting on save. Would be good to either disable that or make it part of https://github.com/wormhole-foundation/wormhole/blob/dev.v2/scripts/lint.sh because it makes the PR harder to review.

My bad, was in a rush. Wrote an issue to add prettier enforcement though! #1773

**Pull request merged**
