### PR TITLE
node: Governor token list update

### PR DESCRIPTION
**Pull request by djb15**
```
Tokens before = 1517
Tokens after = 1518

Tokens added = 2:
<WH_chain_id>-<WH_token_addr>-<token_symbol>

[
 "2-000000000000000000000000bf5495efe5db9ce00f80364c8b423567e58d2110-ezETH",
 "30-000000000000000000000000e3b53af74a4bf62ae5511055290838050bf764df-STG"
]

Tokens removed = 1:
<WH_chain_id>-<WH_token_addr>-<token_symbol>

[
 "1-c5f9fb32f49111ab20c33f2598fc836c113e291881ac21ee29169394011244e4-$WIF"
]

Tokens with changed symbols = 0:
<WH_chain_id>-<WH_token_addr>-<old_token_symbol>-><new_token_symbol>



Tokens with invalid symbols = 0:
<WH_chain_id>-<WH_token_addr>-<token_symbol>

[]

Tokens with significant price drops (>50%) = 30:

[
 {
  "token": "1-dbe7c49c3d365abe845bb853bf8a6e8a42743847fd0611ffba1a410b3f22639e-FORGE",
  "previousPrice": 0.03169102,
  "newPrice": 0.01531496,
  "percentageChange": "-51.7"
 },
 {
  "token": "1-06e44836998a9e52bde7b5182fdbbdde4e2789cbffe5ab0e9762cb13651c8bda-TULIP",
  "previousPrice": 0.190832,
  "newPrice": 0.0947,
  "percentageChange": "-50.4"
 },
 {
  "token": "1-139fc1fba8ff288c85d542130fc2caf2caf15d4dc9fce4ac81c1de0fdd3e5be1-KURO",
  "previousPrice": 0.00014249,
  "newPrice": 0.00005085,
  "percentageChange": "-64.3"
 },
 {
  "token": "1-4a6b1a6b92df4ed3059e120bd0e5e4b6a97fd0e8db832c163a15fd284e4d46c7-DILLY",
  "previousPrice": 0.00031292,
  "newPrice": 0.0001023,
  "percentageChange": "-67.3"
 },
 {
  "token": "1-0b32c16d6e18acb932405c63adbf490ed2e214adf8860590fafcc3c869556b26-",
  "previousPrice": 0.00725634,
  "newPrice": 0.0002563,
  "percentageChange": "-96.5"
 },
 {
  "token": "1-c261d86cf5cf877128ba1f5652e5f3dda599270c1556a15bc0a9aacf8063e563-RIN",
  "previousPrice": 0.07263,
  "newPrice": 0.01984842,
  "percentageChange": "-72.7"
 },
 {
  "token": "2-000000000000000000000000d417144312dbf50465b1c641d016962017ef6240-CQT",
  "previousPrice": 0.03625459,
  "newPrice": 0.01126326,
  "percentageChange": "-68.9"
 },
 {
  "token": "2-000000000000000000000000de5ea375ffbdc8b25a80fe13d631e8ba0ab4bb02-GERA",
  "previousPrice": 0.00015485,
  "newPrice": 0.00002085,
  "percentageChange": "-86.5"
 },
 {
  "token": "2-000000000000000000000000aaaebe6fe48e54f431b0c390cfaf0b017d09d42d-CEL",
  "previousPrice": 0.598487,
  "newPrice": 0.203172,
  "percentageChange": "-66.1"
 },
 {
  "token": "2-000000000000000000000000368c5290b13caa10284db58b4ad4f3e9ee8bf4c9-KKO",
  "previousPrice": 0.00725634,
  "newPrice": 0.0002563,
  "percentageChange": "-96.5"
 },
 {
  "token": "2-000000000000000000000000f64265e65c4529879a7abf467e00d39e39c0b0da-RFKJ",
  "previousPrice": 0.00005448,
  "newPrice": 0.00002534,
  "percentageChange": "-53.5"
 },
 {
  "token": "2-000000000000000000000000f70ce9ee486106882d3dc43ddbd84e0fa71ac2a5-DUCKER",
  "previousPrice": 0.00000348,
  "newPrice": 0.00000172,
  "percentageChange": "-50.6"
 },
 {
  "token": "2-000000000000000000000000766d2fcece1e3eef32aae8711ab886ee95fd5b2a-MVP",
  "previousPrice": 0.22112,
  "newPrice": 0.096759,
  "percentageChange": "-56.2"
 },
 {
  "token": "2-000000000000000000000000a462bde22d98335e18a21555b6752db93a937cff-BOBBY",
  "previousPrice": 0.00005448,
  "newPrice": 0.00002534,
  "percentageChange": "-53.5"
 },
 {
  "token": "3-0000000000000000000000002c71557d2edfedd8330e52be500058a014d329e7-BTL",
  "previousPrice": 0.00119308,
  "newPrice": 0.00048337,
  "percentageChange": "-59.5"
 },
 {
  "token": "4-0000000000000000000000002d6f3dc5b202ccd91db114b592872bca32a7e292-SAUDISHIB",
  "previousPrice": 5.3652e-11,
  "newPrice": 7.887e-12,
  "percentageChange": "-85.3"
 },
 {
  "token": "4-000000000000000000000000bd83010eb60f12112908774998f65761cf9f6f9a-STARS",
  "previousPrice": 0.00039699,
  "newPrice": 0.00000812,
  "percentageChange": "-98.0"
 },
 {
  "token": "4-000000000000000000000000c14a7747cfec02cfea62e72bb93538de6b2078e6-GBL",
  "previousPrice": 0.00683867,
  "newPrice": 0.0029661,
  "percentageChange": "-56.6"
 },
 {
  "token": "4-0000000000000000000000008595f9da7b868b1822194faed312235e43007b49-BTT",
  "previousPrice": 0.00153488,
  "newPrice": 8.90758e-7,
  "percentageChange": "-99.9"
 },
 {
  "token": "4-000000000000000000000000c19fe21b4ef356f2f65894392dde4252aa083605-WSO",
  "previousPrice": 0.00007734,
  "newPrice": 0.00001052,
  "percentageChange": "-86.4"
 },
 {
  "token": "5-000000000000000000000000edcfb6984a3c70501baa8b7f5421ae795ecc1496-META",
  "previousPrice": 0.00000221,
  "newPrice": 2.8036e-7,
  "percentageChange": "-87.3"
 },
 {
  "token": "5-0000000000000000000000008d1566569d5b695d44a9a234540f68d393cdc40d-GAME",
  "previousPrice": 0.00263962,
  "newPrice": 0.00046788,
  "percentageChange": "-82.3"
 },
 {
  "token": "5-000000000000000000000000b140665dde25c644c6b418e417c930de8a8a6ac9-ATRI",
  "previousPrice": 0.00046513,
  "newPrice": 0.00016677,
  "percentageChange": "-64.1"
 },
 {
  "token": "5-00000000000000000000000081382e9693de2afc33f69b70a6c12ca9b3a73f47-DOSE",
  "previousPrice": 0.0007488,
  "newPrice": 0.0003021,
  "percentageChange": "-59.7"
 },
 {
  "token": "5-000000000000000000000000011734f6ed20e8d011d85cf7894814b897420acf-ACRE",
  "previousPrice": 0.00018495,
  "newPrice": 0.00006498,
  "percentageChange": "-64.9"
 },
 {
  "token": "6-000000000000000000000000bbaaa0420d474b34be197f95a323c2ff3829e811-LODE",
  "previousPrice": 4.46,
  "newPrice": 1.38,
  "percentageChange": "-69.1"
 },
 {
  "token": "8-00000000000000000000000000000000000000000000000000000000019e8502-Planets",
  "previousPrice": 0.00055495,
  "newPrice": 0.00003019,
  "percentageChange": "-94.6"
 },
 {
  "token": "16-000000000000000000000000818ec0a7fe18ff94269904fced6ae3dae6d6dc0b-USDC",
  "previousPrice": 0.998149,
  "newPrice": 0.089712,
  "percentageChange": "-91.0"
 },
 {
  "token": "24-000000000000000000000000375488f097176507e39b9653b88fdc52cde736bf-TAROT",
  "previousPrice": 0.03172875,
  "newPrice": 0.01451793,
  "percentageChange": "-54.2"
 },
 {
  "token": "30-00000000000000000000000054a65b16d18527160fafc6fcfebaed47c2976dfa-RFKJ",
  "previousPrice": 0.00005448,
  "newPrice": 0.00002534,
  "percentageChange": "-53.5"
 }
]
```

### CODE REVIEW

**Comment by johnsaigle** [comment]
Any context on this one? Looks like a USDC de-peg which seems a bit alarming.

```
 {
  "token": "16-000000000000000000000000818ec0a7fe18ff94269904fced6ae3dae6d6dc0b-USDC",
  "previousPrice": 0.998149,
  "newPrice": 0.089712,
  "percentageChange": "-91.0"
 },
 ```

**Comment by djb15** [comment]
> Any context on this one? Looks like a USDC de-peg which seems a bit alarming.
> 
> ```
>  {
>   "token": "16-000000000000000000000000818ec0a7fe18ff94269904fced6ae3dae6d6dc0b-USDC",
>   "previousPrice": 0.998149,
>   "newPrice": 0.089712,
>   "percentageChange": "-91.0"
>  },
> ```

Yeah this happens...https://www.coingecko.com/en/coins/multichain-bridged-usdc-moonbeam. That's the nice thing about this summary, we can spot these changes before merging and manually correct. I'll make the change

**Review by bruce-riley — APPROVED** [review]

**Comment by johnsaigle** [comment]
@djb15 any thoughts on putting this on hold until #4053 is merged? That way we could get Scroll's tokens included in the list. (actually there's only one token, but still)

**Comment by djb15** [comment]
> @djb15 any thoughts on putting this on hold until #4053 is merged? That way we could get Scroll's tokens included in the list. (actually there's only one token, but still)

@johnsaigle Fine from my side, let me know when that lands and I can trigger another CI run (will be a new PR but I'll leave this around for now in case anyone else has a different opinion)

**Comment by johnsaigle** [comment]
@djb15 The other PR has been merged so you can go ahead and run this again on `main`

**Comment by djb15** [comment]
Closing to re-trigger from CI

**Comment by djb15** [comment]
Replaced by #4061

**Pull request closed without merging**
