### PR TITLE
node,sdk: Mantle mainnet

### PR DESCRIPTION
**Pull request by evan-gray**
This PR makes the required changes to support Mantle in mainnet. 

It also fixes a CI breakage due to a change in the devnet relayer address. I was unable to pin down the exact cause, but I did take the opportunity to pin the foundry version to a docker image in addition to updating the addresses.

### CODE REVIEW

**Review by panoel — APPROVED** [review]

**Review by djb15 — COMMENTED** [review]
Probably worth adding some more manual tokens that have significant ($200k+ 24h volume)?: https://www.coingecko.com/en/categories/mantle-ecosystem

I would add MNT, METH, JOE & Mantled bridged WETH, USDC and USDT as a minimum

**Comment by evan-gray** [comment]
> Probably worth adding some more manual tokens that have significant ($200k+ 24h volume)?: https://www.coingecko.com/en/categories/mantle-ecosystem
> 
> I would add MNT, METH, JOE & Mantled bridged WETH, USDC and USDT as a minimum

I thought that's what https://github.com/wormhole-foundation/wormhole/pull/3958 was for 😬

**Review by djb15 — APPROVED** [review]
#3958 to add to list of manual tokens

**Review by kcsongor — DISMISSED** [review]

**Review by SEJeff — APPROVED** [review]

**Review by kcsongor — APPROVED** [review]

**Review by SEJeff — APPROVED** [review]

**Review by djb15 — APPROVED** [review]

**Review by claudijd — APPROVED** [review]

**Review by panoel — APPROVED** [review]

**Review by a5-pickle — APPROVED** [review]
Reviewed ethereum and testing directories

**Review by gator-boi — APPROVED** [review]

**Pull request merged**
