### PR TITLE
docs: fix typos with spell checker

### PR DESCRIPTION
**Pull request by bodhi-crypo**
1. fix a bunch of typos with spell checker 
2. Hand-checked to exclude some proprietary writings like Optin

wish can help reduce the overrall typo-related PR

### CODE REVIEW

**Review by SEJeff — COMMENTED** [review]
Please see the [commit naming guidelines](https://github.com/wormhole-foundation/wormhole/blob/main/CONTRIBUTING.md#commit-naming-convention) we don't use the google style "chore" , "fix", etc approach.

Just something like `docs: fix typos with spell checker.`

**Comment by bodhi-crypo** [comment]
> Please see the [commit naming guidelines](https://github.com/wormhole-foundation/wormhole/blob/main/CONTRIBUTING.md?rgh-link-date=2023-12-14T16%3A12%3A00Z#commit-naming-convention) we don't use the google style "chore" , "fix", etc approach.
> 
> Just something like `docs: fix typos with spell checker.`

renamed

**Review by bruce-riley — APPROVED** [review]

**Comment by SEJeff** [comment]
@bodhi-crypo can you rebase the commit as well? If you're not familiar with how to do an interactive rebase, you can do this from your `bodhi-crypo:main` branch:

```bash
git rebase -i HEAD~2
```
An editor will pop up and you can find the line that says `chore(doc):fix typos with spell checker`. At the beginning of that line, change `pick` to `edit`. Then run the command:

```bash
git commit --amend
```

And fix the commit message to match the PR title please.

Then you should be able to do:

```bash
git rebase --continue
```

force push your changes and the PR will be updated.

**Comment by bodhi-crypo** [comment]
> @bodhi-crypo can you rebase the commit as well? If you're not familiar with how to do an interactive rebase, you can do this from your `bodhi-crypo:main` branch:
> 
> ```shell
> git rebase -i HEAD~2
> ```
> 
> An editor will pop up and you can find the line that says `chore(doc):fix typos with spell checker`. At the beginning of that line, change `pick` to `edit`. Then run the command:
> 
> ```shell
> git commit --amend
> ```
> 
> And fix the commit message to match the PR title please.
> 
> Then you should be able to do:
> 
> ```shell
> git rebase --continue
> ```
> 
> force push your changes and the PR will be updated.

done.learn a lot from you guys.

**Review by SEJeff — APPROVED** [review]
Thanks much!

**Review by bruce-riley — APPROVED** [review]

**Comment by bodhi-crypo** [comment]
@SEJeff  It looks like it could be merged to avoid conflicts with later updates.

**Review by SEJeff — APPROVED** [review]

**Review by barnjamin — APPROVED** [review]

**Review by evan-gray — APPROVED** [review]

**Review by kev1n-peters — APPROVED** [review]

**Review by a5-pickle — APPROVED** [review]
Fixing these typos is a great upgarde.

**Review by nik-suri — APPROVED** [review]
Thank you!

**Pull request merged**
