### PR TITLE
Add NatSpec Documentation to Ethereum Contracts

### PR DESCRIPTION
**Pull request by fahimahmedx**
This adds NatSpec documentation to some (but many) of the solidity files used for Wormhole's Ethereum contracts. Issue #3477

### CODE REVIEW

**Comment by barnjamin** [comment]
Hey @fahimahmedx, thanks for taking the time to work on this!

As they are right now, the doc strings seem pretty generic and are missing the context that they should provide to the dev.

e.g.
image

This doc string doesn't add much to a dev's understanding. Could you provide additional context to the docstrings?

for the above example, you'd want to mention that this chain id is the Wormhole Chain Id, potentially to a link with more information

**Comment by fahimahmedx** [comment]
Will update, thank you!

**Comment by SEJeff** [comment]
@fahimahmedx have you had a chance to update this? I'm going through old PRs and trying to get them closed or merged.

**Comment by evan-gray** [comment]
Closing as @barnjamin ’s comment regarding lack of meaningful context in these comments has not been resolved.

**Pull request closed without merging**
